### ISSUE TITLE
interp3d formatting

### ISSUE THREAD

**Issue by xinxindu2006** [dbstein/fast_interp#1]
Hi David, 

As I mentioned in our email exchange, there is 

L=20
interpolater3 = interp3d([-L/2.0,-L/2.0,-2.0], [L/2.0,L/2.0,0.0], ...)  which works and 

L=20
interpolater3 = interp3d([-L/2,-L/2,-2], [L/2,L/2, 0], ...)  which doesn't work and gives the error of "can't unbox heterogeneous list: float64 != int64" (The line number that's being cited is line 592 in fast_interp.py)

You mentioned that the latter doesn't work because L/2 is a float and -2 and 0 are integers and everything should probably be cast as floats

**Comment by dbstein** [comment]
I've just pushed an update that casts everything to the appropriate type and pushes them into numba.typed.List containers.  This should fix this issue, along with some others.
