### ISSUE TITLE
NumbaPendingDeprecationWarning

### ISSUE THREAD

**Issue by weiyuanlou** [dbstein/fast_interp#2]
Hi David:

       Thanks for the fast interpolation code!  
       However I keep encountering the following warning message below.
       I provided some simple code below to generate this warning ( the warning sometimes shows up only at the first time of execution )
       I'm not an expert in using Numba, but I wonder if I use the code differently to prevent this warnings, or if the code can be updated to prevent this?

Thanks.

###################################
NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'a' of function '_interp2d_k3'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "../../../GitHub/fast_interp/fast_interp/fast_interp.py", line 355:
@numba.njit(parallel=True)
def _interp2d_k3(f, xout, yout, fout, a, h, n, p, o, lb, ub):
^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))

###############################################

######   Simple code  to generate the warning  ###########################
import numpy as np 
from fast_interp import interp2d

def f(x,y):
    return x + y

xx = np.linspace(0,1,11)
yy = np.linspace(0,1,11)
xxm, yym = np.meshgrid(xx, yy, indexing='ij')

interp = interp2d([0,0], [1,1], [0.1,0.1], f(xxm,yym))
interp(0.01,0.01)
################################

**Comment by phylars** [comment]
@dbstein Hi David,

This issue exists. Just wish to learn if you are going to fix it up?

Thanks,

**Comment by dbstein** [comment]
This should now be fixed.  Let me know if something from the update I've just pushed doesn't work.
