### ISSUE TITLE
Error in _extrapolate1d_z

### ISSUE THREAD

**Issue by ReadingClouds** [dbstein/fast_interp#4]
Many thanks for writing this and making available. Really useful!
I believe f.shape[1] in _extrapolate1d_z line 74:
        ih = f.shape[1] - (o - ix)
should be 
        ih = f.shape[2] - (o - ix)
(Actually first spotted by Leif Denby). 
Obv I could fork, fix and request a pull, but I thought it'd be simpler if you can fix. as just one character!

**Comment by dbstein** [comment]
Thanks for finding.  Fixed!
